config/routes.rb
Rails.application.routes.draw do
  resources :proyectos
  root 'proyectos#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
    validates :name, presence: true, allow_blank: false
    validates :description, presence: true, allow_blank: false
    validates :state, presence: true, allow_blank: false

    def self.search(search)
        where("state iLIKE ?", "%#{search}%")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]
  include ActionController::HttpAuthentication::Basic::ControllerMethods
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :index
  # GET /proyectos
  # GET /proyectos.json
  def index
    if params[:search]
      @proyectos = Proyecto.search(params[:search])
    else
      @proyectos = Proyecto.all
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyecto_params
      params.require(:proyecto).permit(:name, :description, :starting_date, :ending_date, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorProyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto, local: true) do |form| %>
  <% if proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% proyecto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nombre:' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description, 'Descripción:' %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :starting_date, 'Fecha de comienzo' %>
    <%= form.date_select :starting_date %>
  </div>

  <div class="field">
    <%= form.label :ending_date, 'Fecha de termino' %>
    <%= form.date_select :ending_date %>
  </div>

  <div class="field">
    <%= form.label :state, 'Estado' %>
    <%= form.select :state, [ 'Propuesta', 'En progreso', 'Terminado'] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h1>Editing Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

app/views/proyectos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dashboard</h1>
<form >
        <%= form_tag(proyectos_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Filtrar estado (propuesta, en progreso o terminado)", style:' width:300px'; %>
        <button type="submit">Buscar</button>
        <% end %>
</form>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Fecha de comienzo</th>
      <th>Fecha de termino</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
        <td><%= proyecto.name %></td>
        <td><%= proyecto.description %></td>
        <td><%= proyecto.starting_date %></td>
        <td><%= proyecto.ending_date %></td>
        <td><%= proyecto.state %></td>
        <td><%= link_to 'Show', proyecto %></td>
        <td><%= link_to 'Edit', edit_proyecto_path(proyecto) %></td>
        <td><%= link_to 'Destroy', proyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyecto', new_proyecto_path %>

app/views/proyectos/new.html.erb
<h1>Nuevo Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Dashboard', proyectos_path %>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @proyecto.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @proyecto.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @proyecto.starting_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @proyecto.ending_date %>
</p>

<p>
  <strong>State:</strong>
  <%= @proyecto.state %>
</p>

<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Dashboard', proyectos_path %>